/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'thumbnailUrl' : string,
  'createdAt' : Time,
  'description' : string,
  'price' : bigint,
  'enrollmentCount' : bigint,
}
export interface Enrollment {
  'id' : string,
  'user' : Principal,
  'completed' : boolean,
  'enrolledAt' : Time,
  'courseId' : string,
}
export type ExperienceLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type ExternalBlob = Uint8Array;
export interface Post {
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'experience' : ExperienceLevel,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPost' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, string, bigint, string],
    Course
  >,
  'enrollInCourse' : ActorMethod<[string, string], Enrollment>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[string], [] | [Course]>,
  'getCoursesByCreator' : ActorMethod<[Principal], Array<Course>>,
  'getUserEnrollments' : ActorMethod<[Principal], Array<Enrollment>>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserEnrolled' : ActorMethod<[Principal, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];